### ISSUE TITLE
now-weekly-breakthrough.csv Not Updated for 11 Days

### ISSUE THREAD

**Issue by RuijingZ** [nychealth/coronavirus-data#253] opened 2022-07-18 23:27 UTC
Hi there,

weekly breakthrough file has not been updated for 11 days. Could you kindly upload the data?
https://github.com/nychealth/coronavirus-data/blob/master/latest/now-weekly-breakthrough.csv

Thanks!

**Comment by hbpartonnyc** [comment] 2022-07-21 18:07
Duplicate of #251 

We recently stopped updating our now-weekly-breakthrough file as we evaluate our methods for presenting outcome data by vaccination status. The number of unvaccinated people is calculated by taking the total estimated city population minus the number of those fully or partially vaccinated. However, as more NYC residents become vaccinated, the size of our unvaccinated population approaches zero. And for some groups, we are observing more vaccinated individuals than estimated population. [More about inconsistencies in vaccination rates](https://github.com/nychealth/covid-vaccine-data#zip-codes-and-zip-code-tabulation-areas-zctas).

We continue to work on our methodology to ensure the data we provide are as accurate and transparent as possible. Data comparing cumulative cases, hospitalizations and deaths by vaccination status can still be found in [breakthrough-summary](https://github.com/nychealth/coronavirus-data/blob/master/latest/breakthrough-summary.csv).

**Closed by hbpartonnyc** 2022-07-21 18:07 UTC
