### ISSUE TITLE
Disagreement in hospitalizations between weekly breakthrough an 7-day average

### ISSUE THREAD

**Issue by blm14** [nychealth/coronavirus-data#252] opened 2022-07-15 11:42 UTC
the now-weekly-breakthrough.csv file shows on 6/19/2022 that there were 217 hospitalized vaccinated and boosted, 190 hospitalized vaccinated + unboosted, and 227 hospitalized unvaccinated. That's a total about 600 people.

the now-data-by-day.csv file shows 95 hospitalizations on 6/19/2022. How can this be? Is one of them showing NEW hospitalizations and the other CURRENT hospitalizations?

**Comment by blm14** [comment] 2022-07-17 12:21
I note that within 4 hours of my posting this, the vaccinated vs unvaccinated numbers were removed from the site, with no explanation, no description of exactly what the issue was, how it will be fixed, when it will be fixed, and (this is petty but that's how I feel this morning) no mention of this bug as being related to the change...

Can we get some explanation of what happened, what caused it, when it will be fixed?

**Comment by hbpartonnyc** [comment] 2022-07-21 18:19
> the now-weekly-breakthrough.csv file shows on 6/19/2022 that there were 217 hospitalized vaccinated and boosted, 190 hospitalized vaccinated + unboosted, and 227 hospitalized unvaccinated. That's a total about 600 people.
> 
> the now-data-by-day.csv file shows 95 hospitalizations on 6/19/2022. How can this be? Is one of them showing NEW hospitalizations and the other CURRENT hospitalizations?

The [now-weekly-breakthrough](https://github.com/nychealth/coronavirus-data/blob/master/latest/now-weekly-breakthrough.csv) file shows weekly counts and rates, so the numbers for 6/19/2022 are for the period from June 13 to June 19, 2022. It should also be noted that this file does not include counts and rates for NYC residents who were partially vaccinated. The [now-data-by-day file](https://github.com/nychealth/coronavirus-data/blob/master/latest/now-data-by-day.csv), however, shows daily outcome counts regardless of vaccination status.

**Comment by hbpartonnyc** [comment] 2022-07-21 18:20
> I note that within 4 hours of my posting this, the vaccinated vs unvaccinated numbers were removed from the site, with no explanation, no description of exactly what the issue was, how it will be fixed, when it will be fixed, and (this is petty but that's how I feel this morning) no mention of this bug as being related to the change...
> 
> Can we get some explanation of what happened, what caused it, when it will be fixed?

Duplicate of #251 

We recently stopped updating our now-weekly-breakthrough file as we evaluate our methods for presenting outcome data by vaccination status. The number of unvaccinated people is calculated by taking the total estimated city population minus the number of those fully or partially vaccinated. However, as more NYC residents become vaccinated, the size of our unvaccinated population approaches zero. And for some groups, we are observing more vaccinated individuals than estimated population. [More about inconsistencies in vaccination rates](https://github.com/nychealth/covid-vaccine-data#zip-codes-and-zip-code-tabulation-areas-zctas).

We continue to work on our methodology to ensure the data we provide are as accurate and transparent as possible. Data comparing cumulative cases, hospitalizations and deaths by vaccination status can still be found in [breakthrough-summary](https://github.com/nychealth/coronavirus-data/blob/master/latest/breakthrough-summary.csv).

**Closed by hbpartonnyc** 2022-07-21 18:20 UTC
