### ISSUE TITLE
Probable Hospitalizations?

### ISSUE THREAD

**Issue by GumbyTheGreen1** [nychealth/coronavirus-data#47] opened 2020-04-22 05:08 UTC
The "probable deaths" that you started publishing on the 14th are currently increasing NYC's total death toll by about 50%. Could we also say that there are probable hospitalizations that would similarly increase the total hospitalization count by around 50%? Or are those already factored into the published figure?

**Comment by mmontesanonyc** [comment] 2020-04-23 15:29
There's not a case definition for a "probable COVID hospitalization." 

Testing is indicated for anybody sick enough to be hospitalized, so we don't expect there to be a significant population of people who are hospitalized with COVID symptoms but not tested for it.

**Comment by xrisfg** [comment] 2020-04-23 16:05
Related question: What are the sources for "probable deaths"?

I infer from above that these deaths occur outside hospital settings, since they would have been tested had they been admitted.

I also note from comparing probable deaths in probable-confirmed-dod.csv from 4/18 to yesterday that those numbers *decrease* over time. These are getting changed to confirmed deaths, correct? Either they died before test results came in, or is some testing done posthumously?

Thank you for this valuable service.

**Comment by mmontesanonyc** [comment] 2020-04-23 20:38
A definition of "probable COVID-19 deaths" is available in our [Readme](https://github.com/nychealth/coronavirus-data). The source of a probable death is the death certificate, not location of death.

Some people do die before tests results come in, and are initially listed as probable COVID-19 deaths, before being reassigned to confirmed when a positive result returns.

**Comment by GumbyTheGreen1** [comment] 2020-04-25 18:20
If someone is hospitalized and then tested while in the hospital, how is that recorded? Is it first recorded as a non-Covid hospitalization and then changed to a Covid one when the positive test result comes in?

**Closed** 2020-07-20 18:40 UTC
